### ISSUE TITLE
Round Robin Issue

### ISSUE THREAD

**Issue by sarimbinwaseem** [notwld/Scheduler#2]
Hey..! I tried RR and found that Waiting time is going to -1. 

![Screenshot_20230127_111614](https://user-images.githubusercontent.com/42667306/215106323-ed5bc353-75b2-4cff-89ea-a74d9e9d24b0.png)

I looked at the code and backtracked that there might be issue in calculating CT, <strong>maybe</strong>. And also Turn around time is less than burst time.

**Comment by notwld** [comment]
will be fixed in next build
